#!/bin/bash

# Important - only for https://github.com/SonarSource/sonarqube repository
#
# Create a feature branch based on the latest promoted commit of master.
# Naming conventions are respected so jenkins pipeline will be created then the new branch 
# will be manually pushed.
# 
# Usage: featurebranch -s <stack> <name>

while getopts ":s:" opt; do
  case "$opt" in
    s) 
      stack="$OPTARG"
      ;;
  esac
done
shift $(( OPTIND - 1 ))

name="$@"

# validate stack
if [ -z "$stack" ]; then echo "stack is unset"; exit 1; fi
supportedstacks=("batch" "compute" "large" "server" "web")
if ! [[ "${supportedstacks[@]}" =~ "${stack}" ]]; then
    echo "$stack is not valid. Supported values are: ${supportedstacks[*]}"
    exit 1
fi

echo "stack:   $stack"
echo "feature: $name"

# current branch
branch="$(git rev-parse --abbrev-ref HEAD)"

# latest promoted git commit
promotedsha1="$(git for-each-ref --format='%(*committerdate:raw)%(committerdate:raw) %(refname) %(*objectname) %(objectname)' refs/tags | grep latest-gold-$branch |  sort -n -r| awk '{ print $4 }' | head -1)"

newbranchname="feature/$stack/$name"
echo "create branch $newbranchname from commit $promotedsha1 of branch $branch"
git checkout -b $newbranchname $promotedsha1